const fs = require('fs');

let content = fs.readFileSync('src/App.tsx', 'utf8');

content = content.replace(/const handleAddStudent =([\s\S]*?)saveStudentsState\(\[\.\.\.students, studentNode\]\);/g, "const handleAddStudent =$1addDocument('students', studentNode);");
content = content.replace(/const handleUpdateStudent = \(updatedStudent: Student\) => {\s*const updated = students\.map[^\n]*\n\s*saveStudentsState\(updated\);\s*};/g, "const handleUpdateStudent = (updatedStudent: Student) => {\n    updateDocument('students', updatedStudent);\n  };");
content = content.replace(/const handleBulkAddStudents = \([\s\S]*?saveStudentsState\(\[\.\.\.students, \.\.\.nodes\]\);\s*};/g, "const handleBulkAddStudents = (newStudentsList: Omit<Student, 'id'>[]) => {\n    newStudentsList.forEach(item => {\n      addDocument('students', {\n        ...item,\n        id: `std_${Math.random().toString(36).substring(7)}_${Math.random().toString(36).substring(7)}`\n      });\n    });\n  };");
content = content.replace(/const handleDeleteStudent = \(id: string\) => {\s*const updated = students.filter[^\n]*\n\s*saveStudentsState\(updated\);\s*};/g, "const handleDeleteStudent = (id: string) => {\n    deleteDocument('students', id);\n  };");

content = content.replace(/const handleAddClass = \([\s\S]*?saveClassesState\(\[\.\.\.classes, newClassNode\]\);\s*};/g, "const handleAddClass = (className: string) => {\n    const trimmed = className.trim();\n    if (!trimmed) return;\n    const exists = classes.some(c => c.name.toLowerCase() === trimmed.toLowerCase());\n    if (exists) return;\n    const newClassNode: ClassItem = {\n      id: `class_${Math.random().toString(36).substring(7)}`,\n      name: trimmed\n    };\n    addDocument('classes', newClassNode);\n  };");
content = content.replace(/const handleDeleteClass = \(id: string\) => {\s*saveClassesState\([\s\S]*?\);\s*};/g, "const handleDeleteClass = (id: string) => {\n    deleteDocument('classes', id);\n  };");
content = content.replace(/const handleUpdateClass = \([\s\S]*?saveClassesState\([\s\S]*?\);\s*};/g, "const handleUpdateClass = (updatedClass: ClassItem) => {\n    updateDocument('classes', updatedClass);\n  };");

content = content.replace(/const handleAddSubject = \([\s\S]*?saveSubjectsState\(\[\.\.\.subjects, newSubjectNode\]\);\s*};/g, "const handleAddSubject = (subjectName: string) => {\n    const trimmed = subjectName.trim();\n    if (!trimmed) return;\n    const exists = subjects.some(s => s.name.toLowerCase() === trimmed.toLowerCase());\n    if (exists) return;\n    const newSubjectNode: SubjectItem = {\n      id: `subj_${Math.random().toString(36).substring(7)}`,\n      name: trimmed\n    };\n    addDocument('subjects', newSubjectNode);\n  };");
content = content.replace(/const handleDeleteSubject = \(id: string\) => {\s*saveSubjectsState\([\s\S]*?\);\s*};/g, "const handleDeleteSubject = (id: string) => {\n    deleteDocument('subjects', id);\n  };");
content = content.replace(/const handleUpdateSubject = \([\s\S]*?saveSubjectsState\([\s\S]*?\);\s*};/g, "const handleUpdateSubject = (updatedSubject: SubjectItem) => {\n    updateDocument('subjects', updatedSubject);\n  };");

content = content.replace(/const handleAddTeacher = \([\s\S]*?saveTeachersState\(\[\.\.\.teachers, teacherNode\]\);\s*};/g, "const handleAddTeacher = (newTeacher: Omit<Teacher, 'id'>) => {\n    const teacherNode: Teacher = {\n      ...newTeacher,\n      id: `t_${Math.random().toString(36).substring(7)}`\n    };\n    addDocument('teachers', teacherNode);\n  };");
content = content.replace(/const handleDeleteTeacher = \(id: string\) => {\s*saveTeachersState\([\s\S]*?\);\s*};/g, "const handleDeleteTeacher = (id: string) => {\n    deleteDocument('teachers', id);\n  };");
content = content.replace(/const handleUpdateTeacher = \([\s\S]*?saveTeachersState\([\s\S]*?\);\s*};/g, "const handleUpdateTeacher = (updatedTeacher: Teacher) => {\n    updateDocument('teachers', updatedTeacher);\n  };");

content = content.replace(/const handleSaveMaterial = \([\s\S]*?saveMaterialsState\(\[\.\.\.materials, matNode\]\);\s*};/g, "const handleSaveMaterial = (newMat: Omit<Material, 'id' | 'createdAt'>) => {\n    const matNode: Material = {\n      ...newMat,\n      id: `m_${Math.random().toString(36).substring(7)}`,\n      createdAt: new Date().toISOString()\n    };\n    addDocument('materials', matNode);\n  };");
content = content.replace(/const handleUpdateMaterial = \([\s\S]*?saveMaterialsState\([\s\S]*?\);\s*};/g, "const handleUpdateMaterial = (updatedMat: Material) => {\n    updateDocument('materials', updatedMat);\n  };");
content = content.replace(/const handleToggleMaterial = \([\s\S]*?saveMaterialsState\([\s\S]*?\);\s*};/g, "const handleToggleMaterial = (id: string, currentStatus: 'Aktif' | 'Draft') => {\n    updateDocument('materials', { id, status: currentStatus === 'Aktif' ? 'Draft' : 'Aktif' } as any);\n  };");
content = content.replace(/const handleDeleteMaterial = \(id: string\) => {\s*saveMaterialsState\([\s\S]*?\);\s*};/g, "const handleDeleteMaterial = (id: string) => {\n    deleteDocument('materials', id);\n  };");

content = content.replace(/const handleSaveExam = \([\s\S]*?saveExamsState\(\[examNode, \.\.\.exams\]\);\s*};/g, "const handleSaveExam = (newExam: Omit<Exam, 'id' | 'createdAt'>) => {\n    const examNode: Exam = {\n      ...newExam,\n      id: `ex_${Math.random().toString(36).substring(7)}`,\n      createdAt: new Date().toISOString()\n    };\n    addDocument('exams', examNode);\n  };");
content = content.replace(/const handleUpdateExam = \([\s\S]*?saveExamsState\([\s\S]*?\);\s*};/g, "const handleUpdateExam = (updatedExam: Exam) => {\n    updateDocument('exams', updatedExam);\n  };");
content = content.replace(/const handleDeleteExam = \(examId: string\) => {\s*setExams\([\s\S]*?return updated;\s*}\);\s*};/g, "const handleDeleteExam = (examId: string) => {\n    deleteDocument('exams', examId);\n  };");

content = content.replace(/const handleSaveQuestionBank = \([\s\S]*?let newData;[\s\S]*?saveQuestionBanksState\([\s\S]*?\);\s*}\);/g, "const handleSaveQuestionBank = (bank: Omit<QuestionBank, 'id' | 'createdAt' | 'updatedAt'> | QuestionBank) => {\n    if ('id' in bank) {\n      updateDocument('questionBanks', { ...bank, updatedAt: new Date().toISOString() } as any);\n    } else {\n      const newNode: QuestionBank = {\n        ...bank,\n        id: `qb_${Math.random().toString(36).substring(7)}`,\n        createdAt: new Date().toISOString(),\n        updatedAt: new Date().toISOString()\n      };\n      addDocument('questionBanks', newNode);\n    }\n  };");
content = content.replace(/const handleDeleteQuestionBank = \(id: string\) => {\s*setQuestionBanks\([\s\S]*?return updated;\s*}\);\s*};/g, "const handleDeleteQuestionBank = (id: string) => {\n    deleteDocument('questionBanks', id);\n  };");

content = content.replace(/const handleSaveJournal = \([\s\S]*?saveJournalsState\(\[entryNode, \.\.\.journals\]\);\s*};/g, "const handleSaveJournal = (newEntry: Omit<JournalEntry, 'id'>) => {\n    const entryNode: JournalEntry = {\n      ...newEntry,\n      id: `j_${Math.random().toString(36).substring(7)}`\n    };\n    addDocument('journals', entryNode);\n  };");

content = content.replace(/const handleAddCheatLog = \([\s\S]*?saveCheatLogsState\(\[logNode, \.\.\.cheatLogs\]\);\s*};/g, "const handleAddCheatLog = (log: Omit<CheatLog, 'id' | 'timestamp'>) => {\n    const logNode: CheatLog = {\n      ...log,\n      id: `cl_${Math.random().toString(36).substring(7)}`,\n      timestamp: new Date().toISOString()\n    };\n    addDocument('cheatLogs', logNode);\n  };");

content = content.replace(/const handleSubmitExam = \([\s\S]*?saveSubmissionsState\(\[subNode, \.\.\.submissions\]\);\s*};/g, "const handleSubmitExam = (sub: Omit<ExamSubmission, 'id' | 'submittedAt'>) => {\n    const subNode: ExamSubmission = {\n      ...sub,\n      id: `sub_${Math.random().toString(36).substring(7)}`,\n      submittedAt: new Date().toISOString()\n    };\n    addDocument('submissions', subNode);\n  };");

content = content.replace(/const handleShareToTeacher = \([\s\S]*?id: crypto\.randomUUID\(\),[\s\S]*?}\]\);\s*};/g, "const handleShareToTeacher = (request: Omit<ShareRequest, 'id' | 'createdAt'>) => {\n    const newReq: ShareRequest = {\n      ...request,\n      id: crypto.randomUUID(),\n      createdAt: new Date().toISOString()\n    };\n    addDocument('shareRequests', newReq);\n  };");

content = content.replace(/const handleRespondShare = \([\s\S]*?return req;\n    }\)\);\s*};/g, "const handleRespondShare = (requestId: string, response: 'Accepted' | 'Rejected') => {\n    const req = shareRequests.find(r => r.id === requestId);\n    if (req && req.status === 'Pending') {\n      if (response === 'Accepted') {\n        if (req.itemType === 'Material') {\n          const mat = materials.find(m => m.id === req.itemId);\n          if (mat) {\n            const newMat = { ...mat, teacherId: req.receiverId, classId: [] };\n            delete (newMat as any).id;\n            delete (newMat as any).createdAt;\n            handleSaveMaterial(newMat as any);\n          }\n        } else if (req.itemType === 'QuestionBank') {\n          const qb = questionBanks.find(q => q.id === req.itemId);\n          if (qb) {\n            const newQb = { ...qb, teacherId: req.receiverId, updatedAt: new Date().toISOString() };\n            delete (newQb as any).id;\n            delete (newQb as any).createdAt;\n            handleSaveQuestionBank(newQb as any);\n          }\n        }\n      }\n      updateDocument('shareRequests', { id: requestId, status: response } as any);\n    }\n  };");

content = content.replace(/const handleSaveAnnouncement = \([\s\S]*?saveAnnouncementsState\(\[annNode, \.\.\.announcements\]\);\s*};/g, "const handleSaveAnnouncement = (newAnn: Omit<TeacherAnnouncement, 'id' | 'createdAt'>) => {\n    const annNode: TeacherAnnouncement = {\n      ...newAnn,\n      id: `ann_${Math.random().toString(36).substring(7)}`,\n      createdAt: new Date().toISOString(),\n      isActive: true\n    };\n    addDocument('announcements', annNode);\n  };");
content = content.replace(/const handleDeleteAnnouncement = \(id: string\) => {\s*saveAnnouncementsState\([\s\S]*?\);\s*};/g, "const handleDeleteAnnouncement = (id: string) => {\n    deleteDocument('announcements', id);\n  };");
content = content.replace(/const handleToggleAnnouncement = \(id: string\) => {\s*const updated = announcements.map[^\n]*\n\s*saveAnnouncementsState\(updated\);\s*};/g, "const handleToggleAnnouncement = (id: string) => {\n    const ann = announcements.find(a => a.id === id);\n    if (ann) {\n      updateDocument('announcements', { id, isActive: !ann.isActive } as any);\n    }\n  };");

fs.writeFileSync('src/App.tsx', content);
